### ISSUE TITLE
meta: Upgrade sample application to 0.8.1

### ISSUE THREAD

**Issue by niallthomson** [aws-samples/eks-workshop-v2#1013]
Work towards upgrading all sample application references to 0.8.1 (latest at time of writing).

- [ ] IRSA and Pod identity to account for carts service startup changes #1012 
- [ ] Orders component to account for messaging and configuration changes #1014
- [ ] Extend "Getting Started" lab to execute e2e test to validate any future sample application upgrades
- [ ] Track upstream sample application with renovabot
